### ISSUE TITLE
Solution architecture

### ISSUE THREAD

**Issue by CrispinF** [exeGesIS-SDM/ELM#1]
cloudscribe, including:
SimpleContent
Contact form (we might further develop this component under this project)
Dynamic Auth Policies
User KVP

PP Logger
PP Component Versioning
PP Config Provider
PP Notification Manager

PostgreSQL database

**Comment by JimKerslake** [comment]
Tested this seems to work fine against PgSQL v13.1 locally

**Comment by JimKerslake** [comment]
All above done
CI deploying onto Web16 (from Git develop to staging.)
Manually deployed copy sitting in production.
Pg databases on the new v13 server: Elm_staging  and  Elm_production
CS newsletter license file applied to staging.

**Comment by JimKerslake** [comment]
Moving database for staging site to a separate staging instance of PgSQL 13 - leaving the production one where it was.

**Comment by JimKerslake** [comment]
Staging instance now points to a new (empty) database on the Pg staging server. 

@CrispinF @epennifold @joerichardsESDM  You'll need to recreate your user accounts and anything else you might have done in the old staging Db instance.

**Comment by CrispinF** [comment]
@JimKerslake please add cloudscribe Forms & Surveys module.

**Comment by CrispinF** [comment]
@epennifold @JimKerslake I'm not sure whether this was correctly moved to "Done"... my final comment above asks Jim to add Forms & Surveys, and that has not been done. Did we decide this wasn't needed? Or was this missed?

**Comment by CrispinF** [comment]
Confirmed, not yet done, @JimKerslake to do this soon.

**Comment by CrispinF** [comment]
Done and working, thanks.
