### ISSUE TITLE
Website address

### ISSUE THREAD

**Issue by CrispinF** [exeGesIS-SDM/ELM#3]
For consideration by the client. 
In the interim, and for a staging site, we could use something like elm-hefer-staging.esdm.co.uk and elm-hefer.esdm.co.uk

**Comment by sarahpoppy** [comment]
Yes those are fine as interim please.

**Comment by CrispinF** [comment]
DNS done for the addresses above, pointing at Web-16.

**Comment by CrispinF** [comment]
Sarah has said by email: 

> Okay lets go with hefer-data.org.uk  - please go ahead and buy it & configure, and happy that ownership sites with you.   It may be that there is only a requirement for 2 years during the pilot phase, so I would anticipate that.

**Comment by CrispinF** [comment]
The production site is now running at https://hefer-data.org.uk
The domain has been acquired for 3 years.
The staging site is still at elm-hefer-staging.esdm.co.uk

We can probably close this issue when others have tested this address works. @sarahpoppy
