### ISSUE TITLE
Features from elm_land_parcel not loading in QGIS

### ISSUE THREAD

**Issue by epennifold** [exeGesIS-SDM/ELM#35]
@joerichardsESDM I pulled the ELM land parcels into a QGIS project with the SHINE parcels to run a comparison. 

I could 'zoom' to the ELM land parcels in the correct place when the map is in OSGB, but the layer would not load and I could not see it. QGIS logging said the the CRS was incorrect. QGIS was automatically loading the ELM parcels as WGS84, which is probably wrong?

It might be easier to show you this, but essentially I think the layer _should_ be OSGB but there's something missing (the SRID?) in the ELM data so QGIS is defaulting incorrectly to WGS84.

**Comment by CrispinF** [comment]
If you run this:
SELECT id, pack_request_id, defra_sheet_id, defra_parcel_id, created_date_time, defra_area_ha, geom, ST_SRID(geom)
	FROM public.elm_land_parcel;
you will see that all geometries have SRID of 4326, which explains what Emily saw above.
@joerichardsESDM if the parcel geometry coordinates are actually returned in 27700 (as seems likely) you probably need to state that explicitly when making the geometry records. 4326 may be a default.

**Comment by CrispinF** [comment]
@joerichardsESDM I think this has been resolved... (I accessed the polygons in QGIS and they looked sensible) - was it fully resolved for future parcel loading? any commit comments etc? Has the parcel loading been altered to resolve this?

**Comment by joerichardsESDM** [comment]
Fixed under #7 , SRID is now being explicitly set to 27700 on each feature during loading.
